package org.example.motionville.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

@Configuration
public class DatabaseSchemaMigrationConfig implements BeanPostProcessor {

    private static final Logger log = LoggerFactory.getLogger(DatabaseSchemaMigrationConfig.class);
    private boolean executed = false;

    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
        if (bean instanceof DataSource dataSource && !executed) {
            executed = true;
            repairAppUserEmailVerified(dataSource);
        }
        return bean;
    }

    private void repairAppUserEmailVerified(DataSource dataSource) {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {

            DatabaseMetaData metaData = connection.getMetaData();
            boolean tableExists = checkTableExists(metaData, "app_user")
                    || checkTableExists(metaData, "APP_USER");

            if (tableExists) {
                log.info("Pre-migrating app_user table: ensuring email_verified column exists and contains no nulls...");

                // 1. Add column with default false if it doesn't exist
                try {
                    statement.execute("ALTER TABLE app_user ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE");
                } catch (Exception e) {
                    log.debug("Column creation skipped or already present: {}", e.getMessage());
                }

                // 2. Backfill any existing NULL values to FALSE
                try {
                    statement.execute("UPDATE app_user SET email_verified = FALSE WHERE email_verified IS NULL");
                } catch (Exception e) {
                    log.debug("Null backfill skipped: {}", e.getMessage());
                }

                // 3. Ensure DEFAULT is FALSE
                try {
                    statement.execute("ALTER TABLE app_user ALTER COLUMN email_verified SET DEFAULT FALSE");
                } catch (Exception e) {
                    log.debug("Default constraint update skipped: {}", e.getMessage());
                }

                // 4. Ensure channels has profile_image_url column
                try {
                    statement.execute("ALTER TABLE channels ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(255)");
                } catch (Exception e) {
                    log.debug("channels profile_image_url migration skipped: {}", e.getMessage());
                }

                // 5. Ensure password_reset_tokens table exists
                try {
                    statement.execute("""
                        CREATE TABLE IF NOT EXISTS password_reset_tokens (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            token VARCHAR(128) NOT NULL UNIQUE,
                            user_id BIGINT NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            consumed_at TIMESTAMP WITH TIME ZONE,
                            revoked BOOLEAN NOT NULL DEFAULT FALSE,
                            CONSTRAINT fk_pwd_reset_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
                        )
                    """);
                } catch (Exception e) {
                    log.debug("password_reset_tokens migration skipped: {}", e.getMessage());
                }

                // 6. Ensure categories table description is nullable
                try {
                    statement.execute("ALTER TABLE categories ALTER COLUMN description DROP NOT NULL");
                } catch (Exception e) {
                    log.debug("categories description migration skipped: {}", e.getMessage());
                }

                // 7. Ensure foreign keys cascade on delete for clean user & content deletion
                upgradeForeignKeysToCascade(connection);
            }
        } catch (Exception e) {
            log.debug("Database pre-migration check skipped or failed: {}", e.getMessage());
        }
    }

    private void upgradeForeignKeysToCascade(Connection connection) {
        try {
            DatabaseMetaData metaData = connection.getMetaData();
            String dbProduct = metaData.getDatabaseProductName().toLowerCase();

            if (dbProduct.contains("postgresql") || dbProduct.contains("h2")) {
                log.info("Ensuring foreign key constraints cascade on delete ({})...", dbProduct);
                String findFkQuery = """
                    SELECT
                        tc.table_name,
                        tc.constraint_name,
                        kcu.column_name,
                        ccu.table_name AS foreign_table_name,
                        ccu.column_name AS foreign_column_name
                    FROM information_schema.table_constraints AS tc
                    JOIN information_schema.key_column_usage AS kcu
                        ON tc.constraint_name = kcu.constraint_name
                        AND tc.table_schema = kcu.table_schema
                    JOIN information_schema.constraint_column_usage AS ccu
                        ON ccu.constraint_name = tc.constraint_name
                        AND ccu.table_schema = tc.table_schema
                    JOIN information_schema.referential_constraints AS rc
                        ON rc.constraint_name = tc.constraint_name
                        AND rc.constraint_schema = tc.table_schema
                    WHERE tc.constraint_type = 'FOREIGN KEY'
                      AND lower(tc.table_schema) = 'public'
                      AND lower(ccu.table_name) IN ('app_user', 'channels', 'videos', 'comments', 'playlists')
                      AND upper(rc.delete_rule) != 'CASCADE'
                """;

                List<String[]> fkList = new ArrayList<>();
                try (Statement stmt = connection.createStatement();
                     ResultSet rs = stmt.executeQuery(findFkQuery)) {
                    while (rs.next()) {
                        fkList.add(new String[]{
                                rs.getString("table_name"),
                                rs.getString("constraint_name"),
                                rs.getString("column_name"),
                                rs.getString("foreign_table_name"),
                                rs.getString("foreign_column_name")
                        });
                    }
                }

                for (String[] fk : fkList) {
                    String table = fk[0];
                    String constraint = fk[1];
                    String col = fk[2];
                    String foreignTable = fk[3];
                    String foreignCol = fk[4];

                    try (Statement stmt = connection.createStatement()) {
                        stmt.execute(String.format("ALTER TABLE \"%s\" DROP CONSTRAINT \"%s\"", table, constraint));
                        stmt.execute(String.format("ALTER TABLE \"%s\" ADD CONSTRAINT \"%s\" FOREIGN KEY (\"%s\") REFERENCES \"%s\"(\"%s\") ON DELETE CASCADE",
                                table, constraint, col, foreignTable, foreignCol));
                        log.info("Migrated constraint '{}' on table '{}' to ON DELETE CASCADE", constraint, table);
                    } catch (Exception ex) {
                        log.warn("Could not migrate constraint '{}' on table '{}': {}", constraint, table, ex.getMessage());
                    }
                }
            }
        } catch (Exception ex) {
            log.warn("Foreign key cascade migration skipped: {}", ex.getMessage());
        }
    }

    private boolean checkTableExists(DatabaseMetaData metaData, String tableName) {
        try (ResultSet rs = metaData.getTables(null, null, tableName, new String[]{"TABLE"})) {
            return rs.next();
        } catch (Exception e) {
            return false;
        }
    }
}
