create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    password varchar(255) not null,
    password_hash varchar(255) not null,
    display_name varchar(100) not null,
    avatar_url varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table channels (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_user(id),
    handle varchar(50) not null unique,
    name varchar(100) not null,
    description text,
    banner_url varchar(255),
    created_at timestamp with time zone not null
);

create table categories (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    description varchar(100) not null unique
);

create table videos (
    id bigint generated by default as identity primary key,
    channel_id bigint not null references channels(id),
    category_id bigint references categories(id),
    title varchar(255) not null,
    description text,
    thumbnail_url varchar(255),
    duration_seconds integer not null,
    visibility varchar(20) not null,
    processing_status varchar(20) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    published_at timestamp with time zone
);

create table comments (
    id bigint generated by default as identity primary key,
    video_id bigint not null references videos(id),
    author_id bigint not null references app_user(id),
    parent_comment_id bigint references comments(id),
    body text not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table video_assets (
    id bigint generated by default as identity primary key,
    video_id bigint not null references videos(id),
    asset_url text not null,
    quality varchar(20) not null,
    mime_type varchar(100) not null,
    size_bytes bigint,
    created_at timestamp with time zone not null,
    constraint uq_video_asset_variant unique(video_id, quality, mime_type)
);

create table tags (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique
);

create table video_tags (
    video_id bigint not null references videos(id),
    tag_id bigint not null references tags(id),
    primary key (video_id, tag_id)
);

create table subscriptions (
    id bigint generated by default as identity primary key,
    subscriber_id bigint not null references app_user(id),
    channel_id bigint not null references channels(id),
    subscribed_at timestamp with time zone not null,
    constraint uq_subscription_user_channel unique(subscriber_id, channel_id)
);

create table video_reactions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user(id),
    video_id bigint not null references videos(id),
    reaction varchar(10) not null,
    created_at timestamp with time zone not null,
    constraint uq_video_reaction_user_video unique(user_id, video_id)
);

create table comment_reactions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user(id),
    comment_id bigint not null references comments(id),
    reaction varchar(10) not null,
    created_at timestamp with time zone not null,
    constraint uq_comment_reaction_user_comment unique(user_id, comment_id)
);

create table video_views (
    id bigint generated by default as identity primary key,
    video_id bigint not null references videos(id),
    viewer_id bigint references app_user(id),
    viewed_at timestamp with time zone not null
);

create table watch_history (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user(id),
    video_id bigint not null references videos(id),
    last_position_seconds integer not null,
    last_watched_at timestamp with time zone not null,
    constraint uq_watch_history_user_video unique(user_id, video_id)
);

create table playlists (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_user(id),
    title varchar(150) not null,
    description text,
    visibility varchar(20) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table playlist_videos (
    id bigint generated by default as identity primary key,
    play_list_id bigint not null references playlists(id),
    video_id bigint not null references videos(id),
    position integer not null,
    added_at timestamp with time zone not null,
    constraint uq_playlist_video unique(play_list_id, video_id),
    constraint uq_playlist_position unique(play_list_id, position)
);

create table notifications (
    id bigint generated by default as identity primary key,
    recipient_id bigint not null references app_user(id),
    actor_id bigint references app_user(id),
    comment_id bigint references comments(id),
    type varchar(30) not null,
    message varchar(255) not null,
    created_at timestamp with time zone not null,
    read_at timestamp with time zone
);

create table reports (
    id bigint generated by default as identity primary key,
    reporter_id bigint not null references app_user(id),
    video_id bigint references videos(id),
    comment_id bigint references comments(id),
    reason varchar(30) not null,
    details text,
    status varchar(20) not null,
    created_at timestamp with time zone not null,
    resolved_at timestamp with time zone
);
