create table user_accounts (
    id bigint generated by default as identity primary key,
    email varchar(254) not null unique,
    username varchar(40) not null unique,
    display_name varchar(100) not null,
    password_hash varchar(255) not null,
    bio varchar(1000),
    role varchar(20) not null,
    active boolean not null,
    created_at timestamp with time zone not null
);

create table channels (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references user_accounts(id),
    name varchar(120) not null,
    handle varchar(80) not null unique,
    description varchar(2000),
    created_at timestamp with time zone not null
);

create table videos (
    id bigint generated by default as identity primary key,
    channel_id bigint not null references channels(id),
    title varchar(180) not null,
    description varchar(5000),
    category varchar(80),
    tags varchar(500),
    storage_key varchar(100) not null unique,
    content_type varchar(100) not null,
    visibility varchar(20) not null,
    deleted boolean not null,
    view_count bigint not null,
    created_at timestamp with time zone not null
);

create index idx_videos_channel_created on videos(channel_id, created_at);
create index idx_videos_visibility_created on videos(visibility, created_at);

create table comments (
    id bigint generated by default as identity primary key,
    video_id bigint not null references videos(id),
    user_id bigint not null references user_accounts(id),
    body varchar(2000) not null,
    deleted boolean not null,
    created_at timestamp with time zone not null
);

create index idx_comments_video_created on comments(video_id, created_at);

create table video_likes (
    id bigint generated by default as identity primary key,
    user_id bigint not null references user_accounts(id),
    video_id bigint not null references videos(id),
    created_at timestamp with time zone not null,
    constraint uq_video_likes_user_video unique(user_id, video_id)
);

create table subscriptions (
    id bigint generated by default as identity primary key,
    subscriber_id bigint not null references user_accounts(id),
    channel_id bigint not null references channels(id),
    created_at timestamp with time zone not null,
    constraint uq_subscriptions_subscriber_channel unique(subscriber_id, channel_id)
);

create index idx_subscriptions_channel on subscriptions(channel_id);
